openapi: 3.0.0
x-stoplight:
  id: 366fd12881c11
info:
  title: Public API
  version: 1.0.0
  description: |-
    主にニコニコ全体に共通する情報を取得するためのAPI

    #### Contribute
    このドキュメントは[GitHub](https://github.com/niconicolibs/api)で管理されています。追加・修正はPRを送ってください。
  contact:
    name: niconicolibs
    url: 'https://github.com/niconicolibs/api'
servers:
  - url: 'https://public.api.nicovideo.jp'
tags:
  - name: Users
    description: About Niconico User
  - name: Timeline
    description: About Nicorepo
paths:
  /v1/users.json:
    get:
      summary: Get Users Infomation
      tags:
        - Users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  meta:
                    $ref: ./models/Meta.yaml
                  data:
                    type: array
                    items:
                      $ref: ./models/User.yaml
                required:
                  - meta
              examples:
                example:
                  value:
                    meta:
                      status: 200
                    data:
                      - userId: '2'
                        nickname: 戀塚
                        description: |
                          （・＿・）ノ<br>
                          http://twitter.com/koizuka<br>
                          http://b.hatena.ne.jp/koizuka<br>
                        hasPremiumOrStrongerRights: true
                        hasSuperPremiumOrStrongerRights: false
                        icons:
                          urls:
                            150x150: 'https://secure-dcdn.cdn.nimg.jp/nicoaccount/usericon/0/2.jpg?1305362341'
                            50x50: 'https://secure-dcdn.cdn.nimg.jp/nicoaccount/usericon/s/0/2.jpg?1305362341'
      operationId: get-v1-users.json
      description: |-
        指定したユーザーIDの簡易的なユーザー情報を取得します。<br/>
        https://account.nicovideo.jp/api/public/v1/users.json からもアクセスできます。
      parameters:
        - schema:
            type: array
            items:
              type: integer
          in: query
          name: userIds
          description: ユーザーIDの羅列
          required: true
    parameters: []
  /v2/user.json:
    get:
      summary: Get Own Infomation
      tags:
        - Users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  meta:
                    $ref: ./models/Meta.yaml
                  data:
                    $ref: ./models/OwnUser.yaml
                required:
                  - meta
      operationId: get-v2-user.json
      description: |-
        自分のユーザー情報を取得します。<br>
        https://account.nicovideo.jp/api/public/v2/user.json からもアクセスできます。
      parameters:
        - schema:
            type: string
          in: cookie
          name: user-session
          description: ユーザーセッション
          required: true
  '/v1/timelines/nicorepo/{term}/users/{userId}/{os}/entries.json':
    get:
      summary: Get Nicorepo
      tags:
        - Timeline
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  meta:
                    $ref: ./models/Meta.yaml
        '':
          content:
            application/json:
              schema:
                type: object
                properties:
                  meta:
                    type: object
                    properties:
                      status:
                        type: integer
                      hasNext:
                        type: boolean
                      maxId:
                        type: string
                      minId:
                        type: string
                      errors:
                        type: array
                        items:
                          type: string
                      errorCode:
                        type: string
                      errorMessage:
                        type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        updated:
                          type: string
                        watchContext:
                          type: object
                          properties:
                            parameter:
                              type: object
                              properties:
                                nicorepo:
                                  type: string
                        actor:
                          type: object
                          properties:
                            url:
                              type: string
                            name:
                              type: string
                            icon:
                              type: string
                        title:
                          type: string
                        object:
                          type: object
                          properties:
                            type:
                              type: string
                            url:
                              type: string
                            name:
                              type: string
                            image:
                              type: string
      operationId: get-v1-timelines-nicorepo
      description: ユーザーページに表示されるニコレポを取得します
      parameters:
        - schema:
            type: string
            enum:
              - video
              - program
              - image
              - comitStory
              - article
              - game
          in: query
          name: 'object[type]'
          description: プラットフォームの種類
        - schema:
            type: string
            enum:
              - add
              - onair
          in: query
          name: type
          description: レポートの種類
        - schema:
            type: string
            enum:
              - self
              - followingUser
              - followingChannel
              - followingCommunity
              - followingMylist
          in: query
          description: 表示対象絞り込み
          name: list
        - schema:
            type: string
          in: query
          name: untilId
          description: 更に昔を読み込み用
    parameters:
      - schema:
          type: string
        name: userId
        in: path
        required: true
        description: ユーザーID
      - schema:
          type: string
          enum:
            - pc
            - ios
            - android
        name: os
        in: path
        required: true
        description: OS名
      - schema:
          type: string
          enum:
            - last-1-month
            - last-6-months
        name: term
        in: path
        required: true
