openapi: 3.0.0
x-stoplight:
  id: 366fd12881c11
info:
  title: Public API
  version: 1.0.0
  description: 主にニコニコ全体に共通する情報を取得するためのAPI
servers:
  - url: 'https://public.api.nicovideo.jp'
paths:
  /v1/users.json:
    get:
      summary: Get Users Infomation
      tags:
        - Users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  meta:
                    $ref: '#/components/schemas/Meta'
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
                required:
                  - meta
              examples:
                example:
                  value:
                    meta:
                      status: 200
                    data:
                      - userId: '2'
                        nickname: 戀塚
                        description: |
                          （・＿・）ノ<br>
                          http://twitter.com/koizuka<br>
                          http://b.hatena.ne.jp/koizuka<br>
                        hasPremiumOrStrongerRights: true
                        hasSuperPremiumOrStrongerRights: false
                        icons:
                          urls:
                            150x150: 'https://secure-dcdn.cdn.nimg.jp/nicoaccount/usericon/0/2.jpg?1305362341'
                            50x50: 'https://secure-dcdn.cdn.nimg.jp/nicoaccount/usericon/s/0/2.jpg?1305362341'
      operationId: get-v1-users.json
      description: |-
        指定したユーザーIDの簡易的なユーザー情報を取得します。
        https://account.nicovideo.jp/api/public/v1/users.jsonからもアクセスできます。
      parameters:
        - schema:
            type: array
          in: query
          name: userIds
          description: ユーザーIDの羅列
          required: true
    parameters: []
components:
  schemas:
    Meta:
      title: Meta
      x-stoplight:
        id: knxgt5s0yoi62
      type: object
      properties:
        status:
          type: integer
        errorCode:
          type: string
        errorMessage:
          type: string
      required:
        - status
      x-examples:
        example:
          status: 200
    User:
      title: User
      x-stoplight:
        id: ytbkmo52q3lal
      type: object
      x-examples:
        example:
          userId: '2'
          nickname: 戀塚
          description: |
            （・＿・）ノ<br>
            http://twitter.com/koizuka<br>
            http://b.hatena.ne.jp/koizuka<br>
          hasPremiumOrStrongerRights: true
          hasSuperPremiumOrStrongerRights: false
          icons:
            urls:
              150x150: 'https://secure-dcdn.cdn.nimg.jp/nicoaccount/usericon/0/2.jpg?1305362341'
              50x50: 'https://secure-dcdn.cdn.nimg.jp/nicoaccount/usericon/s/0/2.jpg?1305362341'
      properties:
        userId:
          type: string
          description: ユーザーID
        nickname:
          type: string
          description: ニックネーム
        description:
          type: string
          description: プロフィール
        hasPremiumOrStrongerRights:
          type: boolean
          description: プレミアム会員かどうか
        hasSuperPremiumOrStrongerRights:
          type: boolean
        icons:
          type: object
          required:
            - urls
          description: プロフィールアイコン
          properties:
            urls:
              type: object
              required:
                - 150x150
                - 50x50
              properties:
                150x150:
                  type: string
                50x50:
                  type: string
      required:
        - userId
        - nickname
        - description
        - hasPremiumOrStrongerRights
        - hasSuperPremiumOrStrongerRights
        - icons
