openapi: 3.0.0
x-stoplight:
  id: 366fd12881c11
info:
  title: Public API
  version: 1.0.0
  description: 主にニコニコ全体に共通する情報を取得するためのAPI
  x-logo:
    url: "../static/logo.png"
    backgroundColor: '#FFFFFF'
servers:
  - url: 'https://public.api.nicovideo.jp'
paths:
  /v1/users.json:
    get:
      summary: Get Users Infomation
      tags:
        - User
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  meta:
                    $ref: ./models/Meta.yaml
                  data:
                    type: array
                    items:
                      $ref: ./models/User.yaml
                required:
                  - meta
              examples:
                example:
                  value:
                    meta:
                      status: 200
                    data:
                      - userId: '2'
                        nickname: 戀塚
                        description: |
                          （・＿・）ノ<br>
                          http://twitter.com/koizuka<br>
                          http://b.hatena.ne.jp/koizuka<br>
                        hasPremiumOrStrongerRights: true
                        hasSuperPremiumOrStrongerRights: false
                        icons:
                          urls:
                            150x150: 'https://secure-dcdn.cdn.nimg.jp/nicoaccount/usericon/0/2.jpg?1305362341'
                            50x50: 'https://secure-dcdn.cdn.nimg.jp/nicoaccount/usericon/s/0/2.jpg?1305362341'
      operationId: get-v1-users.json
      description: |-
        指定したユーザーIDの簡易的なユーザー情報を取得します。<br/>
        https://account.nicovideo.jp/api/public/v1/users.json からもアクセスできます。
      parameters:
        - schema:
            type: array
            items:
              type: integer
          in: query
          name: userIds
          description: ユーザーIDの羅列
          required: true
    parameters: []
  /v2/user.json:
    get:
      summary: Get Own Infomation
      tags:
        - User
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  meta:
                    $ref: ./models/Meta.yaml
                  data:
                    $ref: ./models/OwnUser.yaml
                required:
                  - meta
      operationId: get-v2-user.json
      description: |-
        自分のユーザー情報を取得します。<br>
        https://account.nicovideo.jp/api/public/v2/user.json からもアクセスできます。
      parameters:
        - schema:
            type: string
          in: cookie
          name: user-session
          description: ユーザーセッション
          required: true
