title: Meta
x-stoplight:
  id: vwhzvbc093xgj
type: object
properties:
  status:
    type: integer
  errorCode:
    type: string
required:
  - status
x-examples:
  example:
    status: 200
