openapi: 3.0.0
x-stoplight:
  id: emlpc48xqf234
info:
  title: Nicovideo API
  version: 1.0.0
  description: ニコニコ動画に関する情報を取得するAPI
servers:
  - url: 'https://nvapi.nicovideo.jp'
paths:
  '/v1/users/{userId}':
    parameters:
      - schema:
          type: integer
        name: userId
        in: path
        required: true
        description: ユーザーID
    get:
      summary: Get User Information
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  meta:
                    $ref: ./models/Meta.yaml
                  data:
                    type: object
                    properties:
                      user:
                        $ref: ./models/User.yaml
                      relationships:
                        type: object
                        properties:
                          sessionUser:
                            type: object
                            properties:
                              isFollowing:
                                type: boolean
                                default: false
                                description: ログイン中のユーザーがフォローしているか
                          isMe:
                            type: boolean
                            default: false
                            description: ログイン中のユーザーかどうか
                required:
                  - meta
      operationId: get-v1-users-userId
      description: 指定したユーザーIDの詳細なユーザー情報を取得します。
      parameters:
        - schema:
            type: number
            example: 6
          in: header
          name: x-Frontend-Id
          description: '6'
          required: true
        - schema:
            type: string
            example: '0'
          in: header
          name: x-Frontend-version
          description: '0'
          required: true
        - schema:
            type: string
          in: cookie
          name: user-session
          description: ユーザーセッション(なくても機能します)
      tags:
        - User
components:
  schemas: {}
  securitySchemes: {}
